DECLARE
    V_RA ALUNO.RA%TYPE := &RA_ALUNO;
    V_NOTA ALUNO.NOTA%TYPE;
    V_CONCEITO VARCHAR2(12);
BEGIN
    SELECT NOTA
    INTO V_NOTA
    FROM ALUNO
    WHERE RA = V_RA;
    
    V_CONCEITO := 
    CASE
        WHEN V_NOTA <= 7 THEN 'REGULAR'
        WHEN V_NOTA < 9 THEN 'BOM'
        ELSE 'EXCELENTE'
    END;
    DBMS_OUTPUT.PUT_LINE ('Conceito: ' || V_CONCEITO);
END;
