DECLARE
  CURSOR C_ALUNO IS
  SELECT NOTA1, NOTA2, CPF FROM ALUNO;
  V_N1 ALUNO.NOTA1%TYPE;
  V_N2 ALUNO.NOTA2%TYPE;
  V_CPF ALUNO.CPF%TYPE;
  V_M NUMBER(4,2);
BEGIN
  OPEN C_ALUNO;
  LOOP
    FETCH C_ALUNO INTO V_N1, V_N2, V_CPF;
    EXIT WHEN C_ALUNO%NOTFOUND;
    V_M := (V_N1+V_N2)/2;
    UPDATE ALUNO SET MEDIA = V_M WHERE CPF=V_CPF;
  END LOOP;
  CLOSE C_ALUNO;
 END;