DECLARE
  CURSOR C_ALUNO IS
  SELECT NOTA1, NOTA2, CPF FROM ALUNO;
  V_M NUMBER(4,2);
BEGIN
  FOR V_ALUNO IN C_ALUNO
  LOOP
    V_M := (V_ALUNO.NOTA1+V_ALUNO.NOTA2)/2;
    UPDATE ALUNO SET MEDIA = V_M WHERE CPF=V_ALUNO.CPF;
  END LOOP;
END;