DECLARE
  V_RA ALUNO.RA%TYPE;
  V_NOTA ALUNO.NOTA%TYPE;
  V_CONTA NUMBER(2);
  CONTA_ALUNO EXCEPTION;
BEGIN
  SELECT COUNT(RA) INTO V_CONTA FROM ALUNO;
  IF V_CONTA = 10 THEN
    RAISE CONTA_ALUNO;
    ELSE INSERT INTO ALUNO VALUES (20,'SILVA');
  END IF;
  EXCEPTION
  WHEN CONTA_ALUNO THEN
    DBMS_OUTPUT.PUT_LINE('Não foi possível incluir: turma cheia');
END;