DECLARE
    V_RA ALUNO.RA%TYPE := &RA_ALUNO;
    V_NOTA ALUNO.NOTA%TYPE;
    V_CONCEITO VARCHAR2(12);
BEGIN
  
    SELECT NOTA 
    INTO V_NOTA 
    FROM ALUNO 
    WHERE RA = V_RA;
  
    IF V_NOTA <= 7 THEN 
      V_CONCEITO := 'REGULAR';
    ELSIF V_NOTA < 9 THEN 
      V_CONCEITO := 'BOM';
    ELSE V_CONCEITO := 'EXCELENTE';
END IF;
    DBMS_OUTPUT.PUT_LINE ('Conceito: ' || V_CONCEITO);
END;